project:
  name: "Crop video"
  description: "This project contains crop video HDL and testbench files"
  hierarchy:
    - module_name: "Top module"
      files:
        - path: "hdl/crop_vid.v"
      submodules:
        - module_name: "M00_AXIS"
          files:
            - path: "hdl/M00_AXIS.v"
        - module_name: "S00_AXIS"
          files:
            - path: "hdl/S00_AXIS.v"    
        