uvmf:
  interfaces:
    crop_video_config:
      clock: clk
      reset: rst
      reset_assertion_level: 'False'
      config_constraints: []
      config_vars: []
      hdl_typedefs: []
      hvl_typedefs: []
      parameters: []
      ports:
      - name: crop_x
        dir: output
        width: 16
      - name: crop_y
        dir: output
        width: 16
      - name: crop_width
        dir: output
        width: 16
      - name: crop_height
        dir: output
        width: 16
      response_info:
        data: []
        operation: 1'b0
      transaction_constraints:
      - name: crop_x_c
        value: '{ crop_x inside {[1:1919]} }; '
      - name: crop_y_c
        value: '{ crop_y inside {[1:1079]} }; '
      - name: crop_width_c
        value: '{ crop_width < 1920 - crop_x }; '
      - name: crop_height_c
        value: '{ crop_height < 1080 - crop_y }; '
      - name: solve_c
        value: '{ solve crop_x_c before crop_width_c; solve crop_y_c before crop_height_c;}; '  
      transaction_vars:
      - name: crop_x
        type: bit [16-1:0]
        iscompare: 'True'
        isrand: 'True'
      - name: crop_y
        type: bit [16-1:0]
        iscompare: 'True'
        isrand: 'True'
      - name: crop_width
        type: bit [16-1:0]
        iscompare: 'True'
        isrand: 'True'
      - name: crop_height
        type: bit [16-1:0]
        iscompare: 'True'
        isrand: 'True'
