uvmf:
  interfaces:
    crop_video_config:
      clock: clk
      config_constraints: []
      config_vars: []
      existing_library_component: 'True'
      gen_inbound_streaming_driver: 'False'
      hdl_pkg_parameters: []
      hdl_typedefs: []
      hvl_pkg_parameters: []
      hvl_typedefs: []
      parameters: []
      ports:
      - dir: output
        name: crop_x
        reset_value: '''b0'
        width: '16'
      - dir: output
        name: crop_y
        reset_value: '''b0'
        width: '16'
      - dir: output
        name: crop_width
        reset_value: '''b0'
        width: '16'
      - dir: output
        name: crop_height
        reset_value: '''b0'
        width: '16'
      reset: rst
      reset_assertion_level: 'False'
      transaction_constraints:
      - comment: ''
        name: crop_x_c
        value: '{ crop_x inside {[1:1919]} }; '
      - comment: ''
        name: crop_y_c
        value: '{ crop_y inside {[1:1079]} }; '
      - comment: ''
        name: crop_width_c
        value: '{ crop_width < 1920 - crop_x }; '
      - comment: ''
        name: crop_height_c
        value: '{ crop_height < 1080 - crop_y }; '
      - comment: ''
        name: solve_c
        value: '{ solve crop_x_c before crop_width_c; solve crop_y_c before crop_height_c;}; '
      transaction_vars:
      - comment: ''
        iscompare: 'True'
        isrand: 'True'
        name: crop_x
        type: bit [16-1:0]
        unpacked_dimension: ''
      - comment: ''
        iscompare: 'True'
        isrand: 'True'
        name: crop_y
        type: bit [16-1:0]
        unpacked_dimension: ''
      - comment: ''
        iscompare: 'True'
        isrand: 'True'
        name: crop_width
        type: bit [16-1:0]
        unpacked_dimension: ''
      - comment: ''
        iscompare: 'True'
        isrand: 'True'
        name: crop_height
        type: bit [16-1:0]
        unpacked_dimension: ''
      use_dpi_link: 'False'
